-- 1. Buat tabel logbook
CREATE TABLE logbook (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room VARCHAR(10) NOT NULL,
  patient_name VARCHAR(100) DEFAULT NULL,
  tasks JSONB DEFAULT '[]'::jsonb,
  therapies JSONB DEFAULT '[]'::jsonb,
  created_at VARCHAR(8) NOT NULL,
  CONSTRAINT unique_room_created_at UNIQUE (room, created_at)
);

-- 2. Aktifkan Row Level Security (RLS)
ALTER TABLE logbook ENABLE ROW LEVEL SECURITY;

-- 3. Beri izin baca, simpan, dan hapus data
CREATE POLICY "Akses Publik Logbook" ON logbook 
FOR ALL USING (true) WITH CHECK (true);